spaceTimeWindow: Foam::deltaVarintCodec Class Reference
Foam::deltaVarintCodec Class Reference
#include <deltaVarintCodec.H>
Static Public Member Functions
static void write (const fileName &path, const scalarField &field, uint32_t precision=6)
static void write (const fileName &path, const vectorField &field, uint32_t precision=6)
static std::vector< uint8_t > encode (const scalarField &field, uint32_t precision=6)
static std::vector< uint8_t > encode (const vectorField &field, uint32_t precision=6)
static scalarField readScalar (const fileName &path)
static vectorField readVector (const fileName &path)
static scalarField decodeScalar (const std::vector< uint8_t > &buf)
static vectorField decodeVector (const std::vector< uint8_t > &buf)
static bool isDeltaVarintFile (const fileName &path)
static bool isDeltaVarintBuffer (const std::vector< uint8_t > &buf)
static word fileExtension ()
static uint32_t magic ()
Detailed Description
Definition at line 72 of file deltaVarintCodec.H.
Member Function Documentation
decodeScalar()
Foam::scalarField Foam::deltaVarintCodec::decodeScalar (const std::vector< uint8_t > & buf) static
Definition at line 485 of file deltaVarintCodec.C.
Referenced by decryptBoundaryFile().
decodeVector()
Foam::vectorField Foam::deltaVarintCodec::decodeVector (const std::vector< uint8_t > & buf) static
Definition at line 532 of file deltaVarintCodec.C.
Referenced by decryptBoundaryFile().
encode() [1/2]
std::vector< uint8_t > Foam::deltaVarintCodec::encode (const scalarField & field, uint32_t precision = 6) static
Definition at line 404 of file deltaVarintCodec.C.
Referenced by Foam::functionObjects::spaceTimeWindowExtract::writeField().
encode() [2/2]
std::vector< uint8_t > Foam::deltaVarintCodec::encode (const vectorField & field, uint32_t precision = 6) static
Definition at line 442 of file deltaVarintCodec.C.
fileExtension()
static word Foam::deltaVarintCodec::fileExtension () inline static
Definition at line 178 of file deltaVarintCodec.H.
Referenced by decryptBoundaryFile(), main(), and Foam::functionObjects::spaceTimeWindowExtract::writeField().
isDeltaVarintBuffer()
bool Foam::deltaVarintCodec::isDeltaVarintBuffer (const std::vector< uint8_t > & buf) static
Definition at line 604 of file deltaVarintCodec.C.
Referenced by decryptBoundaryFile().
isDeltaVarintFile()
bool Foam::deltaVarintCodec::isDeltaVarintFile (const fileName & path) static
Definition at line 583 of file deltaVarintCodec.C.
magic()
static uint32_t Foam::deltaVarintCodec::magic () inline static
Definition at line 184 of file deltaVarintCodec.H.
readScalar()
Foam::scalarField Foam::deltaVarintCodec::readScalar (const fileName & path) static
Definition at line 273 of file deltaVarintCodec.C.
readVector()
Foam::vectorField Foam::deltaVarintCodec::readVector (const fileName & path) static
Definition at line 336 of file deltaVarintCodec.C.
write() [1/2]
void Foam::deltaVarintCodec::write (const fileName & path, const scalarField & field, uint32_t precision = 6) static
Definition at line 163 of file deltaVarintCodec.C.
Referenced by Foam::functionObjects::spaceTimeWindowExtract::writeField().
write() [2/2]
void Foam::deltaVarintCodec::write (const fileName & path, const vectorField & field, uint32_t precision = 6) static
Definition at line 216 of file deltaVarintCodec.C.
The documentation for this class was generated from the following files:
deltaVarintCodec.H
deltaVarintCodec.C