spaceTimeWindow: Foam::sodiumCrypto Class Reference
Foam::sodiumCrypto Class Reference
#include <sodiumCrypto.H>
Static Public Member Functions
static bool available ()
static bool initialize ()
static bool generateKeypair (std::vector< uint8_t > &publicKey, std::vector< uint8_t > &privateKey)
static std::string toBase64 (const std::vector< uint8_t > &data)
static std::vector< uint8_t > fromBase64 (const std::string &b64)
static void encryptToFile (const fileName &path, const std::vector< uint8_t > &plaintext, const std::vector< uint8_t > &publicKey)
static void encryptToFile (const fileName &path, const std::vector< uint8_t > &plaintext, const std::string &publicKeyBase64)
static std::vector< uint8_t > decryptFromFile (const fileName &path, const std::vector< uint8_t > &publicKey, const std::vector< uint8_t > &privateKey)
static std::vector< uint8_t > decryptFromFile (const fileName &path, const std::string &publicKeyBase64, const std::string &privateKeyBase64)
static bool isEncryptedFile (const fileName &path)
static std::string readPrivateKeyFromStdin (const std::string &prompt)
static std::vector< uint8_t > derivePublicKey (const std::vector< uint8_t > &privateKey)
static std::string derivePublicKeyBase64 (const std::string &privateKeyBase64)
Static Public Attributes
static const word fileExtension
static constexpr uint32_t MAGIC = 0x31434E45
static constexpr size_t PUBLIC_KEY_SIZE = 32
static constexpr size_t PRIVATE_KEY_SIZE = 32
static constexpr size_t HEADER_SIZE = 16
Detailed Description
Definition at line 79 of file sodiumCrypto.H.
Member Function Documentation
available()
bool Foam::sodiumCrypto::available () static
Definition at line 33 of file sodiumCrypto.C.
Referenced by main(), and Foam::functionObjects::spaceTimeWindowExtract::read().
decryptFromFile() [1/2]
std::vector< uint8_t > Foam::sodiumCrypto::decryptFromFile (const fileName & path, const std::vector< uint8_t > & publicKey, const std::vector< uint8_t > & privateKey) static
Definition at line 254 of file sodiumCrypto.C.
Referenced by decryptBoundaryFile().
decryptFromFile() [2/2]
std::vector< uint8_t > Foam::sodiumCrypto::decryptFromFile (const fileName & path, const std::string & publicKeyBase64, const std::string & privateKeyBase64) static
Definition at line 355 of file sodiumCrypto.C.
derivePublicKey()
std::vector< uint8_t > Foam::sodiumCrypto::derivePublicKey (const std::vector< uint8_t > & privateKey) static
Definition at line 452 of file sodiumCrypto.C.
Referenced by main().
derivePublicKeyBase64()
std::string Foam::sodiumCrypto::derivePublicKeyBase64 (const std::string & privateKeyBase64) static
Definition at line 489 of file sodiumCrypto.C.
encryptToFile() [1/2]
void Foam::sodiumCrypto::encryptToFile (const fileName & path, const std::vector< uint8_t > & plaintext, const std::vector< uint8_t > & publicKey) static
Definition at line 163 of file sodiumCrypto.C.
Referenced by Foam::functionObjects::spaceTimeWindowExtract::writeField().
encryptToFile() [2/2]
void Foam::sodiumCrypto::encryptToFile (const fileName & path, const std::vector< uint8_t > & plaintext, const std::string & publicKeyBase64) static
Definition at line 234 of file sodiumCrypto.C.
fromBase64()
std::vector< uint8_t > Foam::sodiumCrypto::fromBase64 (const std::string & b64) static
Definition at line 123 of file sodiumCrypto.C.
Referenced by main(), Foam::functionObjects::spaceTimeWindowExtract::read(), and Foam::functionObjects::spaceTimeWindowExtract::writeField().
generateKeypair()
bool Foam::sodiumCrypto::generateKeypair (std::vector< uint8_t > & publicKey, std::vector< uint8_t > & privateKey) static
Definition at line 63 of file sodiumCrypto.C.
Referenced by main().
initialize()
bool Foam::sodiumCrypto::initialize () static
Definition at line 43 of file sodiumCrypto.C.
isEncryptedFile()
bool Foam::sodiumCrypto::isEncryptedFile (const fileName & path) static
Definition at line 382 of file sodiumCrypto.C.
readPrivateKeyFromStdin()
std::string Foam::sodiumCrypto::readPrivateKeyFromStdin (const std::string & prompt) static
Definition at line 409 of file sodiumCrypto.C.
Referenced by main().
toBase64()
std::string Foam::sodiumCrypto::toBase64 (const std::vector< uint8_t > & data) static
Definition at line 89 of file sodiumCrypto.C.
Referenced by main().
Member Data Documentation
fileExtension
const Foam::word Foam::sodiumCrypto::fileExtension static
Definition at line 86 of file sodiumCrypto.H.
Referenced by decryptBoundaryFile(), main(), and Foam::functionObjects::spaceTimeWindowExtract::writeField().
HEADER_SIZE
constexpr size_t Foam::sodiumCrypto::HEADER_SIZE = 16 static
Definition at line 98 of file sodiumCrypto.H.
MAGIC
constexpr uint32_t Foam::sodiumCrypto::MAGIC = 0x31434E45 static
Definition at line 89 of file sodiumCrypto.H.
PRIVATE_KEY_SIZE
constexpr size_t Foam::sodiumCrypto::PRIVATE_KEY_SIZE = 32 static
Definition at line 95 of file sodiumCrypto.H.
Referenced by main().
PUBLIC_KEY_SIZE
constexpr size_t Foam::sodiumCrypto::PUBLIC_KEY_SIZE = 32 static
Definition at line 92 of file sodiumCrypto.H.
Referenced by Foam::functionObjects::spaceTimeWindowExtract::read().
The documentation for this class was generated from the following files:
sodiumCrypto.H
sodiumCrypto.C