spaceTimeWindow: Foam::functionObjects::spaceTimeWindowExtract Class Reference
Foam::functionObjects::spaceTimeWindowExtract Class Reference
#include <spaceTimeWindowExtract.H>
Public Member Functions
TypeName ("spaceTimeWindowExtract")
spaceTimeWindowExtract (const word &name, const Time &runTime, const dictionary &dict)
virtual ~spaceTimeWindowExtract ()
virtual bool read (const dictionary &dict)
virtual bool execute ()
virtual bool write ()
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToFaces (const GeometricField< Type, fvPatchField, volMesh > &vf) const
template<class Type >
Foam::tmp< Foam::Field< Type > > gatherFieldToMaster (const Field< Type > &localField) const
Protected Member Functions
void writeFoamFileHeader (Ostream &os, const word &className, const word &objectName) const
void initializeSubset ()
void initializeParallelComm ()
void identifyProcessorBoundaryFaces (const boundBox &bb, const labelList &cellsInBox)
void gatherFaceDataToMaster (vectorField &allFaceCentres, scalarField &allFaceWeights, labelList &allFaceCellsInside, labelList &allFaceCellsOutside) const
void gatherAndWriteSubsetMesh ()
void gatherAndWriteInitialFields ()
void writeSubsetMesh ()
void writeInitialFields ()
void writeBoundaryData ()
void updateMetadataTimesteps ()
template<class Type >
tmp< Field< Type > > interpolateToFaces (const GeometricField< Type, fvPatchField, volMesh > &vf) const
template<class Type >
tmp< Field< Type > > gatherFieldToMaster (const Field< Type > &localField) const
template<class Type >
void writeField (const fileName &dir, const word &fieldName, const Field< Type > &field) const
Protected Attributes
point boxMin_
point boxMax_
fileName outputDir_
wordList fieldNames_
IOstreamOption::streamFormat writeFormat_
IOstreamOption::compressionType writeCompression_
bool useDeltaVarint_
label deltaVarintPrecision_
bool useEncryption_
string publicKeyBase64_
autoPtr< fvMeshSubset > meshSubsetPtr_
bool subsetInitialized_
bool meshWritten_
labelList oldInternalFaceIndices_
labelList faceCellsInside_
labelList faceCellsOutside_
scalarList faceWeights_
vectorField faceCentres_
wordList extractedTimesteps_
autoPtr< globalIndex > globalFaceIndexPtr_
label nGlobalFaces_
autoPtr< mapDistribute > outsideCellMapPtr_
labelList remoteFaceIndices_
labelList remoteCellIndices_
labelList remoteCellProcs_
bool hasProcessorBoundaryFaces_
Detailed Description
Definition at line 106 of file spaceTimeWindowExtract.H.
Constructor & Destructor Documentation
spaceTimeWindowExtract()
Foam::functionObjects::spaceTimeWindowExtract::spaceTimeWindowExtract (const word & name, const Time & runTime, const dictionary & dict)
Definition at line 1570 of file spaceTimeWindowExtract.C.
~spaceTimeWindowExtract()
Foam::functionObjects::spaceTimeWindowExtract::~spaceTimeWindowExtract () virtual
Definition at line 1557 of file spaceTimeWindowExtract.C.
Member Function Documentation
execute()
bool Foam::functionObjects::spaceTimeWindowExtract::execute () virtual
Definition at line 1744 of file spaceTimeWindowExtract.C.
gatherAndWriteInitialFields()
void Foam::functionObjects::spaceTimeWindowExtract::gatherAndWriteInitialFields () protected
Definition at line 630 of file spaceTimeWindowExtract.C.
gatherAndWriteSubsetMesh()
void Foam::functionObjects::spaceTimeWindowExtract::gatherAndWriteSubsetMesh () protected
Definition at line 588 of file spaceTimeWindowExtract.C.
gatherFaceDataToMaster()
void Foam::functionObjects::spaceTimeWindowExtract::gatherFaceDataToMaster (vectorField & allFaceCentres, scalarField & allFaceWeights, labelList & allFaceCellsInside, labelList & allFaceCellsOutside) const protected
Definition at line 524 of file spaceTimeWindowExtract.C.
gatherFieldToMaster() [1/2]
template<class Type > tmp<Field<Type> > Foam::functionObjects::spaceTimeWindowExtract::gatherFieldToMaster (const Field< Type > & localField) const protected
gatherFieldToMaster() [2/2]
template<class Type > Foam::tmp<Foam::Field<Type> > Foam::functionObjects::spaceTimeWindowExtract::gatherFieldToMaster (const Field< Type > & localField) const
Definition at line 1410 of file spaceTimeWindowExtract.C.
identifyProcessorBoundaryFaces()
void Foam::functionObjects::spaceTimeWindowExtract::identifyProcessorBoundaryFaces (const boundBox & bb, const labelList & cellsInBox) protected
Definition at line 513 of file spaceTimeWindowExtract.C.
Referenced by initializeSubset().
initializeParallelComm()
void Foam::functionObjects::spaceTimeWindowExtract::initializeParallelComm () protected
Definition at line 505 of file spaceTimeWindowExtract.C.
Referenced by initializeSubset().
initializeSubset()
void Foam::functionObjects::spaceTimeWindowExtract::initializeSubset () protected
Definition at line 74 of file spaceTimeWindowExtract.C.
References boxMax_, boxMin_, faceCellsInside_, faceCellsOutside_, faceCentres_, faceWeights_, globalFaceIndexPtr_, hasProcessorBoundaryFaces_, identifyProcessorBoundaryFaces(), initializeParallelComm(), meshSubsetPtr_, nGlobalFaces_, oldInternalFaceIndices_, remoteCellIndices_, remoteCellProcs_, remoteFaceIndices_, and subsetInitialized_.
interpolateToFaces() [1/2]
template<class Type > tmp<Field<Type> > Foam::functionObjects::spaceTimeWindowExtract::interpolateToFaces (const GeometricField< Type, fvPatchField, volMesh > & vf) const protected
interpolateToFaces() [2/2]
template<class Type > Foam::tmp<Foam::Field<Type> > Foam::functionObjects::spaceTimeWindowExtract::interpolateToFaces (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Definition at line 1298 of file spaceTimeWindowExtract.C.
read()
bool Foam::functionObjects::spaceTimeWindowExtract::read (const dictionary & dict) virtual
Definition at line 1610 of file spaceTimeWindowExtract.C.
References Foam::sodiumCrypto::available(), Foam::sodiumCrypto::fromBase64(), and Foam::sodiumCrypto::PUBLIC_KEY_SIZE.
TypeName()
Foam::functionObjects::spaceTimeWindowExtract::TypeName ("spaceTimeWindowExtract")
updateMetadataTimesteps()
void Foam::functionObjects::spaceTimeWindowExtract::updateMetadataTimesteps () protected
Definition at line 1273 of file spaceTimeWindowExtract.C.
write()
bool Foam::functionObjects::spaceTimeWindowExtract::write () virtual
Definition at line 1784 of file spaceTimeWindowExtract.C.
writeBoundaryData()
void Foam::functionObjects::spaceTimeWindowExtract::writeBoundaryData () protected
Definition at line 1196 of file spaceTimeWindowExtract.C.
writeField()
template<class Type > void Foam::functionObjects::spaceTimeWindowExtract::writeField (const fileName & dir, const word & fieldName, const Field< Type > & field) const protected
Definition at line 1456 of file spaceTimeWindowExtract.C.
References Foam::deltaVarintCodec::encode(), Foam::sodiumCrypto::encryptToFile(), Foam::sodiumCrypto::fileExtension, Foam::deltaVarintCodec::fileExtension(), Foam::sodiumCrypto::fromBase64(), and Foam::deltaVarintCodec::write().
writeFoamFileHeader()
void Foam::functionObjects::spaceTimeWindowExtract::writeFoamFileHeader (Ostream & os, const word & className, const word & objectName) const protected
Definition at line 56 of file spaceTimeWindowExtract.C.
writeInitialFields()
void Foam::functionObjects::spaceTimeWindowExtract::writeInitialFields () protected
Definition at line 1066 of file spaceTimeWindowExtract.C.
writeSubsetMesh()
void Foam::functionObjects::spaceTimeWindowExtract::writeSubsetMesh () protected
Definition at line 870 of file spaceTimeWindowExtract.C.
Member Data Documentation
boxMax_
point Foam::functionObjects::spaceTimeWindowExtract::boxMax_ protected
Definition at line 118 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
boxMin_
point Foam::functionObjects::spaceTimeWindowExtract::boxMin_ protected
Definition at line 115 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
deltaVarintPrecision_
label Foam::functionObjects::spaceTimeWindowExtract::deltaVarintPrecision_ protected
Definition at line 136 of file spaceTimeWindowExtract.H.
extractedTimesteps_
wordList Foam::functionObjects::spaceTimeWindowExtract::extractedTimesteps_ protected
Definition at line 169 of file spaceTimeWindowExtract.H.
faceCellsInside_
labelList Foam::functionObjects::spaceTimeWindowExtract::faceCellsInside_ protected
Definition at line 157 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
faceCellsOutside_
labelList Foam::functionObjects::spaceTimeWindowExtract::faceCellsOutside_ protected
Definition at line 160 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
faceCentres_
vectorField Foam::functionObjects::spaceTimeWindowExtract::faceCentres_ protected
Definition at line 166 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
faceWeights_
scalarList Foam::functionObjects::spaceTimeWindowExtract::faceWeights_ protected
Definition at line 163 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
fieldNames_
wordList Foam::functionObjects::spaceTimeWindowExtract::fieldNames_ protected
Definition at line 124 of file spaceTimeWindowExtract.H.
globalFaceIndexPtr_
autoPtr<globalIndex> Foam::functionObjects::spaceTimeWindowExtract::globalFaceIndexPtr_ protected
Definition at line 174 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
hasProcessorBoundaryFaces_
bool Foam::functionObjects::spaceTimeWindowExtract::hasProcessorBoundaryFaces_ protected
Definition at line 193 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
meshSubsetPtr_
autoPtr<fvMeshSubset> Foam::functionObjects::spaceTimeWindowExtract::meshSubsetPtr_ protected
Definition at line 145 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
meshWritten_
bool Foam::functionObjects::spaceTimeWindowExtract::meshWritten_ protected
Definition at line 151 of file spaceTimeWindowExtract.H.
nGlobalFaces_
label Foam::functionObjects::spaceTimeWindowExtract::nGlobalFaces_ protected
Definition at line 177 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
oldInternalFaceIndices_
labelList Foam::functionObjects::spaceTimeWindowExtract::oldInternalFaceIndices_ protected
Definition at line 154 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
outputDir_
fileName Foam::functionObjects::spaceTimeWindowExtract::outputDir_ protected
Definition at line 121 of file spaceTimeWindowExtract.H.
outsideCellMapPtr_
autoPtr<mapDistribute> Foam::functionObjects::spaceTimeWindowExtract::outsideCellMapPtr_ protected
Definition at line 181 of file spaceTimeWindowExtract.H.
publicKeyBase64_
string Foam::functionObjects::spaceTimeWindowExtract::publicKeyBase64_ protected
Definition at line 142 of file spaceTimeWindowExtract.H.
remoteCellIndices_
labelList Foam::functionObjects::spaceTimeWindowExtract::remoteCellIndices_ protected
Definition at line 187 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
remoteCellProcs_
labelList Foam::functionObjects::spaceTimeWindowExtract::remoteCellProcs_ protected
Definition at line 190 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
remoteFaceIndices_
labelList Foam::functionObjects::spaceTimeWindowExtract::remoteFaceIndices_ protected
Definition at line 184 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
subsetInitialized_
bool Foam::functionObjects::spaceTimeWindowExtract::subsetInitialized_ protected
Definition at line 148 of file spaceTimeWindowExtract.H.
Referenced by initializeSubset().
useDeltaVarint_
bool Foam::functionObjects::spaceTimeWindowExtract::useDeltaVarint_ protected
Definition at line 133 of file spaceTimeWindowExtract.H.
useEncryption_
bool Foam::functionObjects::spaceTimeWindowExtract::useEncryption_ protected
Definition at line 139 of file spaceTimeWindowExtract.H.
writeCompression_
IOstreamOption::compressionType Foam::functionObjects::spaceTimeWindowExtract::writeCompression_ protected
Definition at line 130 of file spaceTimeWindowExtract.H.
writeFormat_
IOstreamOption::streamFormat Foam::functionObjects::spaceTimeWindowExtract::writeFormat_ protected
Definition at line 127 of file spaceTimeWindowExtract.H.
The documentation for this class was generated from the following files:
spaceTimeWindowExtract.H
spaceTimeWindowExtract.C