spaceTimeWindow: spaceTimeWindowInitCase.C File Reference
spaceTimeWindowInitCase.C File Reference
#include "argList.H"
#include "Time.H"
#include "fvMesh.H"
#include "fvMeshSubset.H"
#include "IOdictionary.H"
#include "IFstream.H"
#include "OFstream.H"
#include "volFields.H"
#include "surfaceFields.H"
#include "OSspecific.H"
#include "foamVersion.H"
#include "Tuple2.H"
#include "DynamicList.H"
#include "SortableList.H"
#include "boundBox.H"
#include "deltaVarintCodec.H"
#include "sodiumCrypto.H"
#include <fstream>
#include <sstream>
#include "setRootCase.H"
Functions
void copyFile (const fileName &src, const fileName &dst)
void copyDirectory (const fileName &src, const fileName &dst)
word decryptBoundaryFile (const fileName &encryptedPath, const fileName &outputDir, const std::vector< uint8_t > &publicKey, const std::vector< uint8_t > &privateKey, bool verbose=true)
void writeControlDict (const fileName &targetDir, const dictionary &metadata, const dictionary &sourceControlDict, const word &startTimeName, const word &endTimeName)
void writeInitialField (const fileName &targetDir, const word &fieldName, const word &fieldType, const dictionary &fieldDict, const word &timeName, const polyBoundaryMesh &bMesh)
int main (int argc, char *argv[])
Function Documentation
copyDirectory()
void copyDirectory (const fileName & src, const fileName & dst)
Definition at line 77 of file spaceTimeWindowInitCase.C.
copyFile()
void copyFile (const fileName & src, const fileName & dst)
Definition at line 63 of file spaceTimeWindowInitCase.C.
Referenced by main().
decryptBoundaryFile()
word decryptBoundaryFile (const fileName & encryptedPath, const fileName & outputDir, const std::vector< uint8_t > & publicKey, const std::vector< uint8_t > & privateKey, bool verbose = true)
Definition at line 90 of file spaceTimeWindowInitCase.C.
References Foam::deltaVarintCodec::decodeScalar(), Foam::deltaVarintCodec::decodeVector(), Foam::sodiumCrypto::decryptFromFile(), Foam::sodiumCrypto::fileExtension, Foam::deltaVarintCodec::fileExtension(), and Foam::deltaVarintCodec::isDeltaVarintBuffer().
Referenced by main().
main()
int main (int argc, char * argv[])
Definition at line 579 of file spaceTimeWindowInitCase.C.
References Foam::sodiumCrypto::available(), copyFile(), decryptBoundaryFile(), Foam::sodiumCrypto::derivePublicKey(), Foam::sodiumCrypto::fileExtension, Foam::deltaVarintCodec::fileExtension(), Foam::sodiumCrypto::fromBase64(), Foam::sodiumCrypto::PRIVATE_KEY_SIZE, Foam::sodiumCrypto::readPrivateKeyFromStdin(), and writeControlDict().
writeControlDict()
void writeControlDict (const fileName & targetDir, const dictionary & metadata, const dictionary & sourceControlDict, const word & startTimeName, const word & endTimeName)
Definition at line 291 of file spaceTimeWindowInitCase.C.
Referenced by main().
writeInitialField()
void writeInitialField (const fileName & targetDir, const word & fieldName, const word & fieldType, const dictionary & fieldDict, const word & timeName, const polyBoundaryMesh & bMesh)
Definition at line 391 of file spaceTimeWindowInitCase.C.